#!/usr/bin/env python3
"""Build the manifest for a train/test run and record the run's settings.

Resolves IMAGE_ROOT/MANIFEST/TRAIN_DOMAINS/TEST_DOMAINS/RUN_COMMENT, runs
build_manifest.py with them, then writes them as `export` lines to a file
that submit_train_test.sbatch sources automatically.
"""

from __future__ import annotations

import argparse
import os
import shlex
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent
BUILD_MANIFEST = REPO_ROOT / "build_manifest.py"


def env_or_default(name: str, default: str) -> str:
    return os.environ.get(name, default)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--image-root", default=env_or_default("IMAGE_ROOT", "pollen_labwild_test"))
    parser.add_argument("--metadata", default=env_or_default("METADATA_PATH", ""))
    parser.add_argument("--manifest", default=env_or_default("MANIFEST", "pollen_labwild_test/manifest.csv"))
    parser.add_argument("--train-domains", default=env_or_default("TRAIN_DOMAINS", "wild"))
    parser.add_argument("--test-domains", default=env_or_default("TEST_DOMAINS", "wild"))
    parser.add_argument("--train-ratio", type=float, default=float(env_or_default("TRAIN_TARGET_RATIO", "0.4")))
    parser.add_argument("--val-ratio", type=float, default=float(env_or_default("VAL_TARGET_RATIO", "0.1")))
    parser.add_argument("--test-ratio", type=float, default=float(env_or_default("TEST_TARGET_RATIO", "0.5")))
    parser.add_argument("--seed", type=int, default=int(env_or_default("MANIFEST_SEED", "42")))
    parser.add_argument("--domain-field", default=env_or_default("DOMAIN_FIELD", "image_type"))
    parser.add_argument("--class-field", default=env_or_default("CLASS_FIELD", "species"))
    parser.add_argument("--path-field", default=env_or_default("PATH_FIELD", "filename"))
    parser.add_argument("--run-comment", default=env_or_default("RUN_COMMENT", ""))
    parser.add_argument(
        "--env-file",
        default=env_or_default("ENV_FILE", str(REPO_ROOT / "train_test_env.sh")),
        help="Path to the sourceable env file consumed by submit_train_test.sbatch.",
    )
    parser.add_argument(
        "--skip-build",
        action="store_true",
        help="Skip running build_manifest.py; only (re)write the env file.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    image_root = Path(args.image_root).expanduser().resolve()
    manifest_path = Path(args.manifest).expanduser().resolve()
    metadata_path = Path(args.metadata).expanduser().resolve() if args.metadata else None
    run_comment = args.run_comment or f"{args.train_domains}__{args.test_domains}"

    build_cmd = [
        sys.executable,
        str(BUILD_MANIFEST),
        "--image-root", str(image_root),
        "--manifest", str(manifest_path),
        "--train-domains", args.train_domains,
        "--test-domains", args.test_domains,
        "--train-ratio", str(args.train_ratio),
        "--val-ratio", str(args.val_ratio),
        "--test-ratio", str(args.test_ratio),
        "--seed", str(args.seed),
        "--domain-field", args.domain_field,
        "--class-field", args.class_field,
        "--path-field", args.path_field,
    ]
    if metadata_path:
        build_cmd += ["--metadata", str(metadata_path)]

    if not args.skip_build:
        print("[prepare] " + " ".join(build_cmd), flush=True)
        result = subprocess.run(build_cmd, check=False)
        if result.returncode != 0:
            print("[error] build_manifest.py failed; env file not written", file=sys.stderr, flush=True)
            return result.returncode

    env_vars = {
        "IMAGE_ROOT": str(image_root),
        "MANIFEST": str(manifest_path),
        "TRAIN_DOMAINS": args.train_domains,
        "TEST_DOMAINS": args.test_domains,
        "RUN_COMMENT": run_comment,
    }
    export_lines = [f"export {name}={shlex.quote(value)}" for name, value in env_vars.items()]
    # ":=" only fills unset/empty vars, so this file won't clobber values a caller
    # (e.g. train_test.py) already exported into the job's inherited environment.
    default_lines = [f': "${{{name}:={shlex.quote(value)}}}"' for name, value in env_vars.items()]

    print("\n[env] settings for submit_train_test.sbatch:", flush=True)
    for line in export_lines:
        print(line, flush=True)

    env_file = Path(args.env_file).expanduser().resolve()
    env_file.write_text(
        "# Generated by prepare_train_test.py -- sourced by submit_train_test.sbatch\n"
        + "\n".join(default_lines)
        + "\n"
    )
    print(f"\n[ready] wrote env file: {env_file}", flush=True)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
